# Eig,Eigh for Block UniTensor #372

In [1]:
import cytnx
import numpy as np
print(cytnx.__path__)
print(cytnx.__version__)

['/Users/pcchen/miniforge3/envs/bkut_eig/lib/python3.10/site-packages/cytnx-0.9.6-py3.10-macosx-11.0-arm64.egg/cytnx']
0.9.6


In [2]:
# Create sigma matrices as non-symmetric UniTensors
Sp = cytnx.UniTensor.zeros([2,2]) # sigma^+
Sp[0, 1] = +1.
Sm = cytnx.UniTensor.zeros([2,2]) # sigma^-
Sm[1, 0] = +1.
Sz = cytnx.UniTensor.zeros([2,2]) # sigma^z
Sz[0, 0] = +1.
Sz[1, 1] = -1.
# Create two copies of all sigma matrices for the two sites
Sp1 = Sp.clone().set_name("Sp1").relabels(["i1","j1"])
Sp2 = Sp.clone().set_name("Sp2").relabels(["i2","j2"])
Sm1 = Sm.clone().set_name("Sm1").relabels(["i1","j1"])
Sm2 = Sm.clone().set_name("Sm2").relabels(["i2","j2"])
Sz1 = Sz.clone().set_name("Sz1").relabels(["i1","j1"])
Sz2 = Sz.clone().set_name("Sz2").relabels(["i2","j2"])
# Kronecker product of two sigma matrices at different sites
Sp1Sm2 = cytnx.Contract(Sp1,Sm2).set_name("Sp1Sm2")
Sp1Sm2.permute_(["i1","i2","j1","j2"])
Sm1Sp2 = cytnx.Contract(Sm1,Sp2).set_name("Sm1Sp2")
Sm1Sp2.permute_(["i1","i2","j1","j2"])
Sz1Sz2 = cytnx.Contract(Sz1,Sz2).set_name("Sz1Sz2")
Sz1Sz2.permute_(["i1","i2","j1","j2"])
# Create Hamiltonian as non-symmetric UniTensor
H = Sp1Sm2 + Sm1Sp2 + Sz1Sz2
H.set_name("H non-Symmetric").relabels_(["i1","i2","j1","j2"])
# Print in matrix form to check
print(H.reshape(4,4))
H.print_diagram()

-------- start of print ---------
Tensor name: 
is_diag    : False
contiguous : True

Total elem: 16
type  : Double (Float64)
cytnx device: CPU
Shape : (4,4)
[[1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 ]
 [0.00000e+00 -1.00000e+00 1.00000e+00 0.00000e+00 ]
 [0.00000e+00 1.00000e+00 -1.00000e+00 0.00000e+00 ]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 ]]




-----------------------
tensor Name : H non-Symmetric
tensor Rank : 4
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
           ---------     
          /         \    
   i1 ____| 2     2 |____ j1
          |         |    
   i2 ____| 2     2 |____ j2
          \         /    
           ---------     


In [21]:
HH = H.clone()
HH.print_diagram()
HH.combineBonds(["i1","i2"])
HH.combineBonds(["j1","j2"])
HH.set_rowrank_(1)
HH.print_diagram()

-----------------------
tensor Name : H non-Symmetric
tensor Rank : 4
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
           ---------     
          /         \    
   i1 ____| 2     2 |____ j1
          |         |    
   i2 ____| 2     2 |____ j2
          \         /    
           ---------     
-----------------------
tensor Name : H non-Symmetric
tensor Rank : 2
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
           ---------     
          /         \    
   i1 ____| 4     4 |____ j1
          \         /    
           ---------     


In [24]:
E, V = cytnx.linalg.Eigh(HH, is_V=True, row_v=False)
E.print_diagram()
print(E)
V.print_diagram()
print(V)

-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : True
on device   : cytnx device: CPU
          ---------     
         /         \    
   0 ____| 4     4 |____ 1
         \         /    
          ---------     
-------- start of print ---------
Tensor name: 
is_diag    : True
contiguous : True

Total elem: 4
type  : Double (Float64)
cytnx device: CPU
Shape : (4)
[-2.00000e+00 0.00000e+00 1.00000e+00 1.00000e+00 ]




-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
          ---------     
         /         \    
   0 ____| 4     4 |____ 1
         \         /    
          ---------     
-------- start of print ---------
Tensor name: 
is_diag    : False
contiguous : True

Total elem: 16
type  : Double (Float64)
cytnx device: CPU
Shape : (4,4)
[[0.00000e+00 -0.00000e+00 1.00000e+00 0.00000e+00 ]
 [7.07107e-01 7.07107e-01 0.00000e+00 0.00000e+00 ]
 [-7.07107e-01 7.071

In [5]:
S, U, Vdag = cytnx.linalg.Svd (H)
S.print_diagram()
U.print_diagram()
print(S)
print(U)

-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : True
on device   : cytnx device: CPU
               ---------     
              /         \    
   _aux_L ____| 4     4 |____ _aux_R
              \         /    
               ---------     
-----------------------
tensor Name : 
tensor Rank : 3
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
           ---------     
          /         \    
   i1 ____| 2     4 |____ _aux_L
          |         |    
   i2 ____| 2       |        
          \         /    
           ---------     
-------- start of print ---------
Tensor name: 
is_diag    : True
contiguous : True

Total elem: 4
type  : Double (Float64)
cytnx device: CPU
Shape : (4)
[2.00000e+00 1.00000e+00 1.00000e+00 3.35470e-17 ]




-------- start of print ---------
Tensor name: 
is_diag    : False
contiguous : True

Total elem: 16
type  : Double (Float64)
cytnx device: CPU
Shape : (2,2,4)
[[[0.00000e+00 1.00000e+00 0

In [3]:
eigenvalues, eigenvectors = cytnx.linalg.Eigh(H, is_V=True, row_v=False)
print(eigenvalues)
eigenvalues.print_diagram()

-------- start of print ---------
Tensor name: 
is_diag    : True
contiguous : True

Total elem: 4
type  : Double (Float64)
cytnx device: CPU
Shape : (4)
[-2.00000e+00 0.00000e+00 1.00000e+00 1.00000e+00 ]




-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : True
on device   : cytnx device: CPU
          ---------     
         /         \    
   0 ____| 4     4 |____ 1
         \         /    
          ---------     


In [4]:
eigenvectors.print_diagram()
print(eigenvectors)

-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
          ---------     
         /         \    
   0 ____| 4     4 |____ 1
         \         /    
          ---------     
-------- start of print ---------
Tensor name: 
is_diag    : False
contiguous : True

Total elem: 16
type  : Double (Float64)
cytnx device: CPU
Shape : (4,4)
[[0.00000e+00 -0.00000e+00 1.00000e+00 0.00000e+00 ]
 [7.07107e-01 7.07107e-01 0.00000e+00 0.00000e+00 ]
 [-7.07107e-01 7.07107e-01 0.00000e+00 0.00000e+00 ]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 ]]






In [6]:
print(eigenvectors[:,0])
eigenvectors[:,0].print_diagram()

-------- start of print ---------
Tensor name: 
is_diag    : False
contiguous : True

Total elem: 4
type  : Double (Float64)
cytnx device: CPU
Shape : (4)
[0.00000e+00 7.07107e-01 -7.07107e-01 0.00000e+00 ]




-----------------------
tensor Name : 
tensor Rank : 1
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
         --------     
        /        \    
        |      4 |____ 0
        \        /    
         --------     


In [13]:
H.print_diagram()
eigenvalues.print_diagram()

-----------------------
tensor Name : H non-Symmetric
tensor Rank : 4
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
           ---------     
          /         \    
   i1 ____| 2     2 |____ j1
          |         |    
   i2 ____| 2     2 |____ j2
          \         /    
           ---------     
-----------------------
tensor Name : 
tensor Rank : 2
block_form  : False
is_diag     : True
on device   : cytnx device: CPU
          ---------     
         /         \    
   0 ____| 4     4 |____ 1
         \         /    
          ---------     


In [3]:
M = H.get_block().numpy().reshape(4,4)
print(M)
eigenvalues, eigenvectors = np.linalg.eigh(M)
print(eigenvalues)
print(eigenvectors)

[[ 1.  0.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  0.  1.]]
[-2.  0.  1.  1.]
[[ 0.          0.          1.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [-0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [8]:
for i in range(4):
    print(i)
    print(eigenvectors[:, i] )
    print(M @ eigenvectors[:, i] - eigenvalues[i] * eigenvectors[:, i])

0
[ 0.          0.70710678 -0.70710678  0.        ]
[0. 0. 0. 0.]
1
[0.         0.70710678 0.70710678 0.        ]
[0. 0. 0. 0.]
2
[1. 0. 0. 0.]
[0. 0. 0. 0.]
3
[0. 0. 0. 1.]
[0. 0. 0. 0.]


In [25]:
# Supposes H is a UniTensor that is already created as in Listing 43
# Create bonds with U(1) symmetry
bi = cytnx.Bond(cytnx.BD_IN, [cytnx.Qs(+1)>>1, cytnx.Qs(-1)>>1],\
                [cytnx.Symmetry.U1()])
bo = cytnx.Bond(cytnx.BD_OUT, [cytnx.Qs(+1)>>1, cytnx.Qs(-1)>>1],\
                [cytnx.Symmetry.U1()])
# Initialize U(1) symmetric UniTensor
H_sym = cytnx.UniTensor([bi,bi,bo,bo]).set_name("H symmetric")\
                        .relabels(["i1","i2","j1","j2"])
# Copy data from the non-symmetric UniTensor H
H_sym.convert_from(H)
print(H_sym) # Check the blocks

-------- start of print ---------
Tensor name: H symmetric
braket_form : True
is_diag    : False
[OVERALL] contiguous : True
BLOCK [#0]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [0] U1(1)  -->| 1     1 |-->  [0] U1(1)
                 |         |
   [0] U1(1)  -->| 1     1 |-->  [0] U1(1)
                 |         |
                 -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1,1,1,1)
[[[[1.00000e+00 ]]]]

BLOCK [#1]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [0] U1(1)   -->| 1     1 |-->  [0] U1(1)
                  |         |
   [1] U1(-1)  -->| 1     1 |-->  [1] U1(-1)
                  |         |
                  -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1,1,1,1)
[[[[-1.00000e+00 ]]]]

BLOCK [#2]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symm

In [58]:
E, V = cytnx.linalg.Eigh(H_sym, is_V=True, row_v=False)
E.print_diagram()
print(E)
V.print_diagram()
print(V)

-----------------------
tensor Name : 
tensor Rank : 2
contiguous  : True
valid blocks : 3
is diag   : True
on device   : cytnx device: CPU
           row           col 
              -----------    
              |         |    
   _aux_L  -->| 4     4 |-->  _aux_R
              |         |    
              -----------    

-------- start of print ---------
Tensor name: 
braket_form : True
is_diag    : True
[OVERALL] contiguous : True
 *is_diag: True
BLOCK [#0]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [0] U1(-2)  -->| 1     1 |-->  [0] U1(-2)
                  |         |
                  -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1)
[1.00000e+00 ]

 *is_diag: True
BLOCK [#1]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [1] U1(0)  -->| 2     2 |-->  [1] U1(0)
                 |         |
    

In [53]:
Vd = V.Dagger().permute(["_aux_L", "i1", "i2"]).set_rowrank(1).relabels(["_aux_R", "j1", "j2"])
Vd.print_diagram()
X = cytnx.Contracts([V, E, Vd]).set_rowrank(2)
X.print_diagram()
print(cytnx.linalg.Norm(X-H_sym).item())

-----------------------
tensor Name : 
tensor Rank : 3
contiguous  : False
valid blocks : 4
is diag   : False
on device   : cytnx device: CPU
           row           col 
              -----------    
              |         |    
   _aux_R  -->| 4     2 |-->  j1
              |         |    
              |       2 |-->  j2
              |         |    
              -----------    

-----------------------
tensor Name : 
tensor Rank : 4
contiguous  : True
valid blocks : 6
is diag   : False
on device   : cytnx device: CPU
       row           col 
          -----------    
          |         |    
   i1  -->| 2     2 |-->  j1
          |         |    
   i2  -->| 2     2 |-->  j2
          |         |    
          -----------    

4.440892098500626e-16


In [54]:
print(V)

-------- start of print ---------
Tensor name: 
braket_form : True
is_diag    : False
[OVERALL] contiguous : True
BLOCK [#0]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [1] U1(-1)  -->| 1     1 |-->  [0] U1(-2)
                  |         |
   [1] U1(-1)  -->| 1       |
                  |         |
                  -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1,1,1)
[[[1.00000e+00 ]]]

BLOCK [#1]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [0] U1(1)   -->| 1     2 |-->  [1] U1(0)
                  |         |
   [1] U1(-1)  -->| 1       |
                  |         |
                  -----------

Total elem: 2
type  : Double (Float64)
cytnx device: CPU
Shape : (1,1,2)
[[[7.07107e-01 7.07107e-01 ]]]

BLOCK [#2]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  ------

In [55]:
print(E)

-------- start of print ---------
Tensor name: 
braket_form : True
is_diag    : True
[OVERALL] contiguous : True
 *is_diag: True
BLOCK [#0]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [0] U1(-2)  -->| 1     1 |-->  [0] U1(-2)
                  |         |
                  -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1)
[1.00000e+00 ]

 *is_diag: True
BLOCK [#1]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [1] U1(0)  -->| 2     2 |-->  [1] U1(0)
                 |         |
                 -----------

Total elem: 2
type  : Double (Float64)
cytnx device: CPU
Shape : (2)
[-2.00000e+00 0.00000e+00 ]

 *is_diag: True
BLOCK [#2]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [2] U1(2)  -->| 1     1 |-->  [2] U1(2)
                

In [56]:
E

-------- start of print ---------
Tensor name: 
braket_form : True
is_diag    : True
[OVERALL] contiguous : True
 *is_diag: True
BLOCK [#0]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                  -----------
                  |         |
   [0] U1(-2)  -->| 1     1 |-->  [0] U1(-2)
                  |         |
                  -----------

Total elem: 1
type  : Double (Float64)
cytnx device: CPU
Shape : (1)
[1.00000e+00 ]

 *is_diag: True
BLOCK [#1]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [1] U1(0)  -->| 2     2 |-->  [1] U1(0)
                 |         |
                 -----------

Total elem: 2
type  : Double (Float64)
cytnx device: CPU
Shape : (2)
[-2.00000e+00 0.00000e+00 ]

 *is_diag: True
BLOCK [#2]
 |- []   : Qn index 
 |- Sym(): Qnum of correspond symmetry
                 -----------
                 |         |
   [2] U1(2)  -->| 1     1 |-->  [2] U1(2)
                